### ISSUE TITLE
preinstall script forces root on linux only install

### ISSUE THREAD

**Issue by hardillb** [matboehmer/node-red-contrib-eddystone#3]
The preinstall script means that this node can only ever be installed at root on linux.

The underlying bleno library will works happily on OSx and you can run on Linux as a none root user by setting the right flags on the nodejs binary (https://github.com/sandeepmistry/bleno#running-on-linux)

Could you remove this preinstall script so it doesn't fail if not installed as root.

**Comment by matboehmer** [comment]
Happy to do so. Could you please send a pull request?

**Comment by hardillb** [comment]
Yeah can do, will probably be this evening
